### ISSUE TITLE
akka.ConfigurationException: Logger specified in config can't be loaded

### ISSUE THREAD

**Issue by MatthieuNICOLAS** [BuggleInc/webPLM#90]
The application crashed during the night from 24/25 August.
The logs of the application show the following error repeating itself several times.
During that time, the New Relic charts show the CPU load increasing (it nearly doubled) as well as the memory, from 2.57GB to 4.28GB.

[This thread](http://stackoverflow.com/questions/29366986/akka-configuration-exception-logger-specified-cant-be-loaded) talks about the error which occurred. In our case, it may also due to the RAM. Indeed, the memory was nearly full with more than 90% used at the time. 

```
plm_1           | [WARN] [08/24/2016 20:34:02.134] [New I/O worker #39] [EventStream(akka://application)] Logger log1-Logging$DefaultLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
plm_1           | error while starting up loggers
plm_1           | akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.Logging$DefaultLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
plm_1           | 	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:116)
plm_1           | 	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:115)
plm_1           | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
plm_1           | 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
plm_1           | 	at scala.util.Try$.apply(Try.scala:192)
plm_1           | 	at scala.util.Failure.recover(Try.scala:216)
plm_1           | 	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:115)
plm_1           | 	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:110)
plm_1           | 	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
plm_1           | 	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
plm_1           | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
plm_1           | 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
plm_1           | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
plm_1           | 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
plm_1           | 	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:110)
plm_1           | 	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
plm_1           | 	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:623)
plm_1           | 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:620)
plm_1           | 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:617)
plm_1           | 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:617)
plm_1           | 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:634)
plm_1           | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
plm_1           | 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
plm_1           | 	at controllers.Application.<init>(Application.scala:23)
plm_1           | 	at controllers.Application$$FastClassByGuice$$b5b6aa19.newInstance(<generated>)
plm_1           | 	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
plm_1           | 	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
plm_1           | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
plm_1           | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
plm_1           | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
plm_1           | 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
plm_1           | 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
plm_1           | 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
plm_1           | 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
plm_1           | 	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321)
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$27.apply(Routes.scala:341)
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$27.apply(Routes.scala:341)
plm_1           | 	at play.core.routing.HandlerInvokerFactory$$anon$12$$anon$13.call(HandlerInvoker.scala:89)
plm_1           | 	at play.core.routing.NewRelicWrapperInvoker.call(HandlerInvoker.scala:33)
plm_1           | 	at play.core.routing.TaggingInvoker.call(HandlerInvoker.scala:32)
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(Routes.scala:341)
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(Routes.scala:341)
plm_1           | 	at play.core.routing.GeneratedRouter.call(GeneratedRouter.scala:95)
plm_1           | 	at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:340)
plm_1           | 	at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:336)
plm_1           | 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
plm_1           | 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
plm_1           | 	at play.api.routing.Router$class.handlerFor(Router.scala:38)
plm_1           | 	at play.core.routing.GeneratedRouter.handlerFor(GeneratedRouter.scala:86)
plm_1           | 	at play.api.http.DefaultHttpRequestHandler.routeRequest(HttpRequestHandler.scala:170)
plm_1           | 	at play.api.http.JavaCompatibleHttpRequestHandler.routeRequest(HttpRequestHandler.scala:201)
plm_1           | 	at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:166)
plm_1           | 	at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:165)
plm_1           | 	at scala.Option.flatMap(Option.scala:171)
plm_1           | 	at play.api.GlobalSettings$class.onRouteRequest(GlobalSettings.scala:165)
plm_1           | 	at play.api.DefaultGlobal$.onRouteRequest(GlobalSettings.scala:212)
plm_1           | 	at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:110)
plm_1           | 	at play.api.DefaultGlobal$.onRequestReceived(GlobalSettings.scala:212)
plm_1           | 	at play.api.http.GlobalSettingsHttpRequestHandler.handlerForRequest(HttpRequestHandler.scala:183)
plm_1           | 	at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:38)
plm_1           | 	at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:37)
plm_1           | 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
plm_1           | 	at scala.util.Try$.apply(Try.scala:192)
plm_1           | 	at scala.util.Success.map(Try.scala:237)
plm_1           | 	at play.core.server.Server$class.sendHandler$1(Server.scala:37)
plm_1           | 	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:58)
plm_1           | 	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57)
plm_1           | 	at scala.util.Either$RightProjection.flatMap(Either.scala:522)
plm_1           | 	at play.core.server.Server$class.getHandlerFor(Server.scala:57)
plm_1           | 	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33)
plm_1           | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139)
plm_1           | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139)
plm_1           | 	at scala.util.Either.fold(Either.scala:99)
plm_1           | 	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:127)
plm_1           | 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
plm_1           | 	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62)
plm_1           | 	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
plm_1           | 	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
plm_1           | 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
plm_1           | 	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
plm_1           | 	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
plm_1           | 	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
plm_1           | 	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
plm_1           | 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
plm_1           | 	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
plm_1           | 	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
plm_1           | 	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
plm_1           | 	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
plm_1           | 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
plm_1           | 	at org.jboss.netty.bootstrap.NettyDispatcher.upstreamDispatcher(NettyDispatcher.java:67)
plm_1           | 	at org.jboss.netty.bootstrap.NettyDispatcher.handleUpstream(NettyDispatcher.java:47)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
plm_1           | 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
plm_1           | 	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
plm_1           | 	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
plm_1           | 	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
plm_1           | 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
plm_1           | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
plm_1           | 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
plm_1           | 	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
plm_1           | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
plm_1           | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
plm_1           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
plm_1           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
plm_1           | 	at java.lang.Thread.run(Thread.java:745)
plm_1           | Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
plm_1           | 	at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:185)
plm_1           | 	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:114)
plm_1           | 	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:113)
plm_1           | 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
plm_1           | 	at scala.util.Try$.apply(Try.scala:192)
plm_1           | 	at scala.util.Success.map(Try.scala:237)
plm_1           | 	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
plm_1           | 	... 108 more
plm_1           | ! @71778jfb0 - Internal server error, for (GET) [/] ->
plm_1           |  
plm_1           | play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ProvisionException: Unable to provision, see the following errors:
plm_1           | 
plm_1           | 1) Error injecting constructor, akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.Logging$DefaultLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
plm_1           |   at controllers.Application.<init>(Application.scala:22)
plm_1           |   while locating controllers.Application
plm_1           | 
plm_1           | 1 error]]
plm_1           | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [com.typesafe.play.play-server_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [com.typesafe.play.play-server_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [com.typesafe.play.play-server_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at scala.util.Either$RightProjection.flatMap(Either.scala:522) [org.scala-lang.scala-library-2.11.7.jar:na]
plm_1           | 	at play.core.server.Server$class.getHandlerFor(Server.scala:57) [com.typesafe.play.play-server_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [com.typesafe.play.play-netty-server_2.11-2.4.2.jar:2.4.2]
plm_1           | Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
plm_1           | 
plm_1           | 1) Error injecting constructor, akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.Logging$DefaultLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
plm_1           |   at controllers.Application.<init>(Application.scala:22)
plm_1           |   while locating controllers.Application
plm_1           | 
plm_1           | 1 error
plm_1           | 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[com.google.inject.guice-4.0.jar:na]
plm_1           | 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[com.google.inject.guice-4.0.jar:na]
plm_1           | 	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$27.apply(Routes.scala:341) ~[web-plm.web-plm-1.3.0.jar:1.3.0]
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$27.apply(Routes.scala:341) ~[web-plm.web-plm-1.3.0.jar:1.3.0]
plm_1           | 	at play.core.routing.HandlerInvokerFactory$$anon$12$$anon$13.call(HandlerInvoker.scala:89) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at play.core.routing.NewRelicWrapperInvoker.call(HandlerInvoker.scala:33) ~[newrelic.jar:2.4.2]
plm_1           | 	at play.core.routing.TaggingInvoker.call(HandlerInvoker.scala:32) ~[com.typesafe.play.play_2.11-2.4.2.jar:2.4.2]
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(Routes.scala:341) ~[web-plm.web-plm-1.3.0.jar:1.3.0]
plm_1           | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(Routes.scala:341) ~[web-plm.web-plm-1.3.0.jar:1.3.0]
```

**Comment by mquinson** [comment]
I'm not sure of what to do with this report. When (under which conditions) will we be able to close it?

**Comment by sliencing** [comment]
have fun
